Ans

List vs NumPy Array (Memory & Performance)

Python List
NumPy Array
Different data types allowed
Same data type only
More memory use
Less memory use
Slow calculations
Very fast (vectorized)
Loop required
Built-in operations

Program (Element-wise Multiplication)

In [1]:
import numpy as np

# Python Lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]

result_list = [a*b for a, b in zip(list1, list2)]
print("List multiplication:", result_list)

# NumPy Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_array = arr1 * arr2
print("NumPy multiplication:", result_array)

List multiplication: [4, 10, 18]
NumPy multiplication: [ 4 10 18]


2 Broadcasting in NumPy

Broadcasting ka matlab hai different shape arrays par automatic operation apply karna without copying data.
NumPy smaller array ko automatically expand kar deta hai.

In [2]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([10,20,30])

result = A + B

print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


3 Missing Values in Pandas

Missing values matlab data unavailable hai.
Representation:
NaN
None

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Age": [20, 25, np.nan, 30],
    "Salary": [30000, np.nan, 40000, 50000]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

Detect Missing Values

In [ ]:
print(df.isnull())

Replace with Column Mean

In [ ]:
df_filled = df.fillna(df.mean())

print("After replacing missing values:")
print(df_filled)

4 Boolean Indexing

Boolean indexing me condition True hone par rows select hoti hain.

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [22, 25, 30, 28, 35],
    "Salary": [30000, 40000, 50000, 45000, 60000],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"],
    "Experience": [1, 3, 5, 4, 7]
}

df = pd.DataFrame(data)

filtered = df[(df["Age"] > 25) & (df["Salary"] > 40000)]

print(filtered)

5 groupby() Function

groupby() data ko categories me divide karta hai aur aggregation (mean, sum, count) apply karta hai.

In [3]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [50000, 40000, 60000, 45000, 55000]
}

df = pd.DataFrame(data)

avg_salary = df.groupby("Department")["Salary"].mean()

print(avg_salary)

Department
Finance    55000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64
